[package]
name = "Xcetus"
version = "1.0.0"
published-at = "0x9e69acc50ca03bc943c4f7c5304c2a6002d507b51c11913b247159c60422c606"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.23.1" }
MoveSTL = { git = "https://github.com/CetusProtocol/move-stl.git", subdir = "sui", rev = "mainnet-v1.23.1" }
cetus = { git = "https://github.com/CetusProtocol/cetus-token-interface.git", subdir = "cetus", rev = "mainnet" }

[addresses]
xcetus = "0x9e69acc50ca03bc943c4f7c5304c2a6002d507b51c11913b247159c60422c606"
sui =  "0x2"
