# testnet
# --------------------------
[package]
name = "CetusClmm"
version = "1.0.0"
published-at = "0x837dddad95c6741474cde3e414a2eebccbeae81d0b378f193d00381bdaf0da62"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "sui-v1.0.0" }
MoveSTL = { git = "https://github.com/CetusProtocol/move-stl.git", subdir = "sui", rev = "testnet-sui-v1.0.0" }
IntegerMate = { git = "https://github.com/CetusProtocol/integer-mate.git", subdir = "sui", rev = "testnet-sui-v1.0.0" }

[addresses]
integer_mate = "0x32ba8c0298964e26161b3b44375ac39eeab6b29207e00c5f44368426096eb902"
move_stl = "0x4b0b447943cef3944b29cbbf73faa19b466f98ad8cb468ef28b8640b1c8fd48a"
cetus_clmm = "0x837dddad95c6741474cde3e414a2eebccbeae81d0b378f193d00381bdaf0da62"
